import type { Metadata } from "next";
import "./globals.css";
import Logout from "@/components/Logout";
import { NextRequest } from "next/server";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn = cookies().has("token");
  console.log(isLoggedIn);
  return (
    <html lang="en">
      <body>
        {children} {isLoggedIn && <Logout />}
      </body>
    </html>
  );
}
