import type { Metadata } from "next";
import "./globals.css";
import Logout from "@/components/Logout";
import { cookies } from "next/headers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn = cookies().has("token");
  console.log(isLoggedIn);
  return (
    <html lang="en">
      <body className="dark">
          <main>
          {children} {isLoggedIn && <Logout />}
          </main>
      </body>
    </html>
  );
}
